/*
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.languages.mockup.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import uk.ac.kcl.inf.languages.mockup.ui.internal.MockupActivator;

public class UiMockupLanguageUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MockupActivator.getInstance().getInjector("uk.ac.kcl.inf.languages.mockup.UiMockupLanguage");
	}

}
