/*
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.languages.mockup.ide


/**
 * Use this class to register ide components.
 */
class UiMockupLanguageIdeModule extends AbstractUiMockupLanguageIdeModule {
}
