/*
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.languages.mockup.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractUiMockupLanguageScopeProvider extends DelegatingScopeProvider {
}
