/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.languages.mockup.uiMockupLanguage.impl;

import org.eclipse.emf.ecore.EClass;

import uk.ac.kcl.inf.languages.mockup.uiMockupLanguage.Button;
import uk.ac.kcl.inf.languages.mockup.uiMockupLanguage.UiMockupLanguagePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Button</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ButtonImpl extends WidgetImpl implements Button
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ButtonImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return UiMockupLanguagePackage.Literals.BUTTON;
  }

} //ButtonImpl
