/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.languages.mockup.scoping;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.Scopes;
import uk.ac.kcl.inf.languages.mockup.uiMockupLanguage.Entity;
import uk.ac.kcl.inf.languages.mockup.uiMockupLanguage.Screen;
import uk.ac.kcl.inf.languages.mockup.uiMockupLanguage.Widget;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class UiMockupLanguageScopeProvider extends AbstractUiMockupLanguageScopeProvider {
  public IScope scope_Screen_widgets(final Screen screen, final EReference ref) {
    return Scopes.scopeFor(screen.getWidgets());
  }
  
  public IScope scope_Entity_attributes(final Entity entity, final EReference ref) {
    return Scopes.scopeFor(entity.getAttributes());
  }
  
  public IScope scope_Widget_label(final Widget widget, final EReference ref) {
    EObject _eContainer = widget.eContainer();
    final Screen screen = ((Screen) _eContainer);
    return Scopes.scopeFor(screen.getWidgets());
  }
}
