/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.languages.mockup.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class UiMockupLanguageUiModule extends AbstractUiMockupLanguageUiModule {
  public UiMockupLanguageUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
