/*
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.languages.mockup.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class UiMockupLanguageAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("uk/ac/kcl/inf/languages/mockup/parser/antlr/internal/InternalUiMockupLanguage.tokens");
	}
}
