/*
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.languages.mockup.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import uk.ac.kcl.inf.languages.mockup.parser.antlr.internal.InternalUiMockupLanguageParser;
import uk.ac.kcl.inf.languages.mockup.services.UiMockupLanguageGrammarAccess;

public class UiMockupLanguageParser extends AbstractAntlrParser {

	@Inject
	private UiMockupLanguageGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalUiMockupLanguageParser createParser(XtextTokenStream stream) {
		return new InternalUiMockupLanguageParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public UiMockupLanguageGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(UiMockupLanguageGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
