/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.languages.mockup.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import uk.ac.kcl.inf.languages.mockup.UiMockupLanguageRuntimeModule;
import uk.ac.kcl.inf.languages.mockup.UiMockupLanguageStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class UiMockupLanguageIdeSetup extends UiMockupLanguageStandaloneSetup {
  @Override
  public Injector createInjector() {
    UiMockupLanguageRuntimeModule _uiMockupLanguageRuntimeModule = new UiMockupLanguageRuntimeModule();
    UiMockupLanguageIdeModule _uiMockupLanguageIdeModule = new UiMockupLanguageIdeModule();
    return Guice.createInjector(Modules2.mixin(_uiMockupLanguageRuntimeModule, _uiMockupLanguageIdeModule));
  }
}
