/*
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.languages.mockup


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class UiMockupLanguageStandaloneSetup extends UiMockupLanguageStandaloneSetupGenerated {

	def static void doSetup() {
		new UiMockupLanguageStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
